---
engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  eslint:
    enabled: true
    config:
      .eslintrc
    channel: "eslint-3"
  stylelint:
    enabled: true
    config:
      .stylelintrc
  fixme:
    enabled: true
ratings:
  paths:
    - src/**/*.{js,css}
exclude_paths:
  - tests/
  - build/
  - coverage/
